feat(web): changes in terms form ipfs upload
kleros/escrow-v2 pull request #15
Opened 2024-01-06 02:15 UTC by kemuru

2024-01-09 17:09 UTC, jaybuidl approved these changes

2024-01-12 16:52 UTC, alcercu requested changes
There are a couple of `console.log` too, let's remember to remove them before announcing testnet.

2024-01-12 16:52 UTC, alcercu commented on subgraph/mappings/utils.ts
> +export const ZERO = BigInt.fromI32(0)
I think there exists a `BigInt.zero` built in 🤔

2024-01-12 16:52 UTC, alcercu commented on web/src/utils/handleFileUpload.ts
> +      transactionDetails.extraDescriptionUri = fileHash;
There was some discussion regarding using `ipfs://...` to conform with RFC3986, we will need to update `uploadFileToIpfs` to make it return the cids with that format.

2024-01-12 19:06 UTC, kemuru commented
> There are a couple of `console.log` too, let's remember to remove them before announcing testnet.

yep, I'm still using some for testing, will delete them before release

2024-01-12 19:08 UTC, merged