feat(web): new transaction frontend structure, flow, stylings
kleros/escrow-v2 pull request #3
Opened 2023-12-08 02:48 UTC by kemuru

2023-12-11 15:17 UTC, alcercu requested changes

2023-12-11 23:31 UTC, kemuru commented on web/src/utils/calcMinMax.ts
> +  `calc(${minSize}px + (${maxSize} - ${minSize}) * (min(max(100vw, 375px), 1250px) - 375px) / 875)`;
answered in the other kleros-v2 thread, but basically I would go with my function, but changing the name from `calcMinMax` to `responsiveSize`

2023-12-12 14:40 UTC, alcercu commented on web/src/utils/responsiveSize.ts
> +  `calc(${minSize}px + (${maxSize} - ${minSize}) * (min(max(100vw, 375px), 1250px) - 375px) / 875)`;
```suggestion
export const responsiveSize = (minSize: number, maxSize: number, minScreen: number = 375, maxScreen: number = 1250) =>
  `calc(${minSize}px + (${maxSize} - ${minSize}) * (min(max(100vw, ${minScreen}px), ${maxScreen}px) - ${minScreen}px) / (${
    maxScreen - minScreen
  }))`;
```

2023-12-12 14:50 UTC, alcercu approved these changes
lgtm

2023-12-12 14:51 UTC, merged