feat(subgraph): create escrow-v2 subgraph
kleros/escrow-v2 pull request #6
Opened 2023-12-23 03:22 UTC by kemuru

2023-12-27 13:56 UTC, jaybuidl approved these changes

2023-12-28 16:43 UTC, jaybuidl approved these changes

2024-01-02 10:25 UTC, alcercu requested changes

2024-01-02 10:25 UTC, alcercu commented on web/src/pages/NewTransaction/Terms/Payment/DestinationAddress.tsx
> +  const variant = recipientAddress === "" ? "info" : isValid ? "success" : "error";
Too many nested ternaries 🤔 I would suggest this:

```suggestion
  const message =
    recipientAddress ===  "" || isValid
      ? "The ETH address or ENS of the person/entity that will receive the funds."
      : "The ETH address or ENS of the person/entity is not correct.";

  const variant = useMemo(() => {
    if (recipientAddress === "") return "info";
    else if (isValid) return "success";
    else return "error";
  }, [recipientAddress, isValid]);
```

2024-01-03 14:37 UTC, merged